project: 
  type: website
  output-dir: docs/
  render:
  - "*.qmd"

  
website:
  favicon: /images/logo.png
  bread-crumbs: false
  open-graph: true
  page-navigation: true  
  title: "Grundlagenkurs GI-S (QGIS)"
  site-url: https://gisma-courses.github.io/gc-geoinfo
  repo-url: https://github.com/gisma-courses/gc-geoinfo
  repo-actions: [edit, issue]
  search: 
    location: navbar
    type: textbox
  # page-footer: 
  #   center: "[GISMA (2024)](https://github.com/gisma-courses/gc) | [Impressum](../unit00/impressum.html)"
  twitter-card:
    creator: "@gisma"
  comments: false
   # utterances:
   #   repo: gisma-courses/gc-geoinfo
  navbar:
    logo: /images/logo.png
    right:
      - icon: compass
        text: Formales
        href: unit00/unit00-01-formales.qmd
      - icon: question-square-fill
      # - text: "Raumkonzepte"   
      #   menu: 
      #     - unit01/unit01-01.qmd
      #     - unit01/unit01-02.qmd
      #     - unit01/unit01-03.qmd
      #     - unit01/unit01-04.qmd
      #     - unit01/unit01-05.qmd
      # - text: "GIS Konzepte"        
      #   menu: 
      #     - unit02/unit02-01.qmd
      #     - unit02/unit02-02.qmd
      #     - unit02/unit02-03.qmd
      #     - unit02/unit02-04.qmd
      #     - unit02/unit02-05.qmd          
      #     - unit02/unit02-06.qmd   
      # - text: "Relationen"        
      #   menu: 
      #     - unit03/unit03-01.qmd
      #     - unit03/unit03-02.qmd
      #     - unit03/unit03-03.qmd
      #     - unit03/unit03-04.qmd
      #     - unit03/unit03-05.qmd          
      #     - unit03/unit03-06.qmd   
      # - text: "Analysen"        
      #   menu: 
      #     - unit04/unit04-01.qmd
      #     - unit04/unit04-02.qmd
      #     - unit04/unit04-03.qmd
      #     - unit04/unit04-04.qmd
      #     - unit04/unit04-05.qmd          
      #     - unit04/unit04-06.qmd
      # - text: "MCE"        
      #   menu:           
      #     - unit05/unit05-01.qmd
      #     - unit05/unit05-02.qmd
      #     - unit05/unit05-03.qmd
      #     - unit05/unit05-04.qmd
          
  sidebar:
    - title: "Willkommen"
      style: "docked"
      collapse-level: 1
      pinned: true      
      contents:
        - href: index.qmd
        - section: Arbeitsblätter
          contents:
          - href: unit09/unit09-01.qmd
            text: Arbeitsblatt 1 - Warm Up QGIS   
          - href: unit09/unit09-02.qmd
            text: Arbeitsblatt 2 - Geometrien und Attribute 
          - href: unit09/unit09-03.qmd
            text: Arbeitsblatt 3 -  Analysen und Ableitungen
          - href: unit09/unit09-04.qmd
            text: Arbeitsblatt 4 -  Kosten und Kriterien
          - href: unit09/unit09-05.qmd
            text: Arbeitsblatt 5 -  Reproduzierbarkeit und Workflows
          - href: unit09/unit09-06.qmd
            text: Arbeitsblatt 6 - Die Projektarbeit           
        - section: Reader Geographische Raumkonzept 
          contents:
          - text: "---"       
          - text: Reader Geographische Raumkonzept
          - text: "---"
          - text: "---"                   
          - unit01/unit01-01.qmd
          - unit01/unit01-02.qmd
          - unit01/unit01-03.qmd
          - unit01/unit01-04.qmd
          - unit01/unit01-05.qmd
        - section: Reader GI Raumkonzepte
          contents: 
          - text: "---"      
          - text: Reader GIS Raumkonzepte
          - text: "---"
          - text: "---"                    
          - href: unit02/unit02-01.qmd
          - href: unit02/unit02-02.qmd
          - href: unit02/unit02-03.qmd
          - href: unit02/unit02-04.qmd
          - href: unit02/unit02-05.qmd
          - href: unit02/unit02-06.qmd
        - section: "Reader Vektordaten & Attributtabellen"
          contents:
          - text: "---"
          - text: Reader Vektordaten & Attributtabellen
          - text: "---"          
          - text: "---"                    
          - href: unit03/unit03-01.qmd
            text: Fragen und Antworten   
          - href: unit03/unit03-02.qmd
            text: Thematische Abfragen    
          - href: unit03/unit03-03.qmd
            text: Geometrische Abfragen    
          - href: unit03/unit03-04.qmd
            text: Topologische Abfragen 
          - href: unit03/unit03-05.qmd
            text: Zusammnfassung Fragen und Antworten           
        - section: "Reader Räumliche Datenanalyse"
          contents: 
          - text: "---"
          - text: Reader Räumliche Datenanalyse
          - text: "---"          
          - text: "---"                    
          - href: unit04/unit04-01.qmd
            text: Räumliche Analysemethoden
          - href: unit04/unit04-02.qmd
            text: Voronoi Polygone
          - href: unit04/unit04-03.qmd
            text: Informationsloser Raum
          - href: unit04/unit04-04.qmd
            text: Digitale Geländemodelle
          - href: unit04/unit04-05.qmd
            text: Sichtweite und Sichtfeld
          - href: unit04/unit04-06.qmd
            text:  Prozeßbasierte Ableitungen
        - section: "Reader Räumliche Datenanalyse"
          contents: 
          - text: "---"
          - text: Reader Multikriterien und Kostenanalyse
          - text: "---"          
          - text: "---"                    
          - href: unit05/unit05-01.qmd
            text: Multikriterien-Analysen
          - href: unit05/unit05-02.qmd
            text: Eignungsanalysen
          - href: unit05/unit05-03.qmd
            text: Kombination unterschiedlicher Kriterien  
          - href: unit05/unit05-04.qmd
            text: Multikriterien-Multiziel-Analyse              
      #     - href: unit99/coming-soon.qmd
      #       text: "Folien Blocktag 1"    
      # - text: "---"   
      # - section: "Reader räumliche Interpolation"
      #   contents: 
      #     - href: unit99/coming-soon.qmd
      #       text: "Folien Blocktag 1"    
        - section: "Reader Automatisierung von Arbeitsabläufen in QGIS "
          contents: 
          - href: unit99/coming-soon.qmd
            text: "coming soon" 
        - section: "Reader Projektarbeit "
          contents: 
          - href: unit06/unit06-01.qmd
            text: Die Projektarbeit    
          - href: unit06/unit06-02.qmd
            text: Wie entwickle ich ein Projekt?  
          - href: unit06/unit06-03.qmd
            text: Das Exposé 
execute:
  freeze: auto
  echo: false
  message: false
  warning: false
  cache: false  
format: 
  html: 
      include-after-body: css/banner-footer.html
      include-in-header: css/banner-style.html
      code-overflow: wrap
      toc-title: "Inhalt"
      number-sections: false
      highlight-style: github
      theme:
       light: cerulean #css/html-inrae.css
       dark: [lumen, css/theme-dark.scss]
      # code-background: true
      code-copy: true
      css: css/styles.css
      toc: true
      link-external-icon: false
      link-external-newwindow: true
      link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
# filters:
#   - include-files.lua
#   - quarto