project: 
  type: website
  output-dir: docs/
  render:
  - "*.qmd"

  
website:
  favicon: /images/logo.png
  bread-crumbs: false
  open-graph: true
  page-navigation: true  
  title: "Grundlagenkurs GI-S (QGIS)"
  site-url: https://gisma-courses.github.io/gc-geoinfo
  repo-url: https://github.com/gisma-courses/gc-geoinfo
  search: 
    location: navbar
    type: textbox
  # page-footer: 
  #   center: "[GISMA (2024)](https://github.com/gisma-courses/gc) | [Impressum](../unit00/impressum.html)"
  twitter-card:
    creator: "@gisma"
  comments: false
   # utterances:
   #   repo: gisma-courses/gc-geoinfo
  navbar:
    logo: /images/logo.png
    # left:
    #   - icon: question-square-fill
    #     text: FAQ
    #     href: unit00/unit00-faq.qmd
    #   - icon: check2-square

  sidebar:
    # logo: /images/logo.jpg
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Formale Rahmenbedingungen"
        contents:
          - index.qmd
          - unit00/unit00-01-formales.qmd
      - text: "---"   
      - section: Reader Geographische Raumkonzepte
        contents: 
          - href: unit01/unit01-01.qmd
            text: Raum braucht einen Geltungsbereich      
          - href: unit01/unit01-02.qmd
            text: Geographie - räumliche Interpretation der Welt    
          - href: unit01/unit01-03.qmd
            text: Objekte im Raum           
          - href: unit01/unit01-04.qmd
            text: Kodierung der Welt durch Geodatensätze
          - href: unit01/unit01-05.qmd
            text: Zusammenfassung – Geographischer Raum           
      - text: "---"   
      - section: Reader GI Raumkonzepte
        contents: 
          - href: unit02/unit02-01.qmd
            text: Raumrepräsentation in der Geoinformatik 
          - href: unit02/unit02-02.qmd
            text: Koordinaten, Topologie und Dimension   
          - href: unit02/unit02-03.qmd
            text: Datenmodelle für Raumdaten    
          - href: unit02/unit02-04.qmd
            text: Die Vermessung der Welt - Orte  
          - href: unit02/unit02-05.qmd
            text: Die Vermessung der Welt - Koordinaten  
          - href: unit02/unit02-06.qmd
            text: Zusammenfassung GI Raumkonzepte             
      - text: "---"   
      - section: "Reader Vektordaten & Attributtabellen"
        contents: 
          - href: unit03/unit03-01.qmd
            text: Fragen und Antworten   
          - href: unit03/unit03-02.qmd
            text: Thematische Abfragen    
          - href: unit03/unit03-03.qmd
            text: Geometrische Abfragen    
          - href: unit03/unit03-04.qmd
            text: Topologische Abfragen 
          - href: unit03/unit03-05.qmd
            text: Zusammnfassung Fragen und Antworten           
      - text: "---"   
      - section: "Reader Quantitative räumliche Datenanalyse"
        contents: 
          # - href: unit99/coming-soon.qmd
          #   text: "Reader Quantitative räumliche Datenanalyse" 
          - href: unit04/unit04-01.qmd
            text: Räumliche Analysemethoden
          - href: unit04/unit04-02.qmd
            text: Voronoi Polygone
          - href: unit04/unit04-03.qmd
            text: Informationsloser Raum
          - href: unit04/unit04-04.qmd
            text: Digitale Geländemodelle
          - href: unit04/unit04-05.qmd
            text: Sichtweite und Sichtfeld
          - href: unit04/unit04-06.qmd
            text:  Prozeßbasierte Ableitungen
          # - href: unit04/unit04-01.qmd
          #   text: "Räumliche Analysemethoden"
          # - href: unit04/unit04-01.qmd
          #   text: "Räumliche Analysemethoden"
                                                
      - text: "---"   
      - section: "Reader Kostenanalyse"
        contents:
          - href: unit05/unit05-01.qmd
            text: Multikriterien-Analysen
          - href: unit05/unit05-02.qmd
            text: Eignungsanalysen
          - href: unit05/unit05-03.qmd
            text: Kombination unterschiedlicher Kriterien  
          - href: unit05/unit05-04.qmd
            text: Multikriterien-Multiziel-Analyse              
      #     - href: unit99/coming-soon.qmd
      #       text: "Folien Blocktag 1"    
      # - text: "---"   
      # - section: "Reader räumliche Interpolation"
      #   contents: 
      #     - href: unit99/coming-soon.qmd
      #       text: "Folien Blocktag 1"    
      - text: "---"   
      - section: "Reader Automatisierung von Arbeitsabläufen in QGIS "
        contents: 
          - href: unit99/coming-soon.qmd
            text: "coming soon"    
      - text: "---"   
      - section: "Reader Projektarbeit "
        contents: 
          - href: unit06/unit06-01.qmd
            text: Die Projektarbeit    

      #- text: "---"
      #- section: "Machine Learning"
      #  contents:
      #    - Machine_Learning_Session/ML_AOA.qmd
          # - href: https://gisma-courses.github.io/LV-uav-workflow/modules/module-introduction/
          #   text: Basic Readings        
          # - href: https://gisma-courses.github.io/LV-uav-workflow/modules/module-fieldwork/
          #   text: uav/Flight Planning
      - text: "---"
execute:
  freeze: auto
  echo: false
  message: false
  warning: false
  cache: false  
format: 
  html: 
      include-after-body: css/banner-footer.html
      include-in-header: css/banner-style.html
      code-overflow: wrap
      toc-title: "Inhalt"
      number-sections: false
      highlight-style: github
      theme:
       light: cerulean #css/html-inrae.css
       dark: [lumen, css/theme-dark.scss]
      # code-background: true
      code-copy: true
      css: css/styles.css
      toc: true
      link-external-icon: false
      link-external-newwindow: true
      link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
# filters:
#   - include-files.lua
#   - quarto