---
title: Arbeitsblatt 3 - Analysen und Ableitungen
title-block-banner: ../assets/images/splash_L02.png
title-block-banner-color: black

bibliography: ../assets/geoinfo.bib

lang: de
comments: false
---

Digitale Geländemodelle liegen in der Regel als Rasterdaten vor und werden häufig in GIS-Analysen verwendet. Dabei tragen sie sowohl direkt zur Höheninformation als auch indirekt, z.B. als morphometrische oder hydrologische Basisdatensätze, zum prozessorientierten Erkenntnisgewinn bei.


Der Themenkomplex der digitalen Geländemodelle einschließlich ihrer Erstellung auf der Basis unterschiedlicher Fernerkundungssensoren ist vielfältig. Die Materialien des Readers skizzieren verschiedene häufig verwendete Ableitungen und räumliche Filter. Diese Konzepte können auf fast alle Rasterdaten angewendet werden.


## Worum geht es in dieses Arbeitsblatt?

In der Übung werden Sie Informationen aus digitalen Geländemodellen ableiten und sich unter anderem mit räumlichen Filtermethoden beschäftigen. Darüber hinaus werden komplexere Werkzeuge wie die Berechnung eines topographischen Indexes oder des Oberflächenabflusses exemplarisch geübt.


## Lernziele 

Nach dieser Übung können Sie

  * Digitale Geländemodelle in ihrer Vielfalt und Bedeutung einschätzen können 
  * Abgeleitete Rasterdaten mit typischen Werkzeugen (Algorithmen) erzeugen
  * diese abgeleiteten Informationen gezielt in Fragestellungen einsetzen
  * Direkte und statistisch aggregierte Informationen extrahieren


## Benötigte Materialien

### Daten
  * [DGM1 Hessen – Marburg](https://gds.hessen.de/downloadcenter/20260506/3D-Daten/Digitales%20Gel%C3%A4ndemodell%20(DGM1)/Landkreis%20Marburg-Biedenkopf/Marburg%20-%20DGM1.zip) – Amtliches digitales Geländemodell der Geländeoberfläche mit 1 m Rasterweite für Marburg.

  * [Copernicus DEM GLO-30 – Marburg-Kachel als GeoTIFF/COG](https://copernicus-dem-30m.s3.amazonaws.com/Copernicus_DSM_COG_10_N50_00_E008_00_DEM/Copernicus_DSM_COG_10_N50_00_E008_00_DEM.tif) – Digitales Oberflächenmodell (DSM); die Kachel kann in QGIS direkt als Remote-Rasterlayer geladen werden.

  * [CGIAR-CSI SRTM](https://srtm.csi.cgiar.org/srtmdata/) – Nachprozessierte SRTM-Daten als GeoTIFF oder Esri ASCII; die FAQ beschreibt Version 4 als endgültige/finale Veröffentlichung des 3-arc-second-Produkts.

  * [SRTM 30 m Tile Downloader](https://dwtkns.com/srtm30m/) – Interaktive Oberfläche zum Download einzelner SRTM-30-m-Kacheln; erfordert einen [NASA Earthdata Login](https://urs.earthdata.nasa.gov/users/new).

  * [NASA Earthdata: Shuttle Radar Topography Mission (SRTM)](https://www.earthdata.nasa.gov/data/instruments/srtm) – Offizielle NASA-Informationsseite zur SRTM-Mission und zum Datensatz.

  * [GDAL: SRTMHGT-Format](https://gdal.org/drivers/raster/srtmhgt.html) – Technische Beschreibung des SRTM-HGT-Rasterformats für die Verarbeitung in GDAL/QGIS.

  * [OpenDEM Deutschland](https://opendem.info/downloads/srtm_germany_dtm.zip) – Aus SRTM abgeleitetes und korrigiertes DTM für Deutschland; die [Info-Seite zur SRTM-Verarbeitung](https://opendem.info/srtm_processing.html) sollte vor der Nutzung gelesen werden.

  * [OpenDEM Europa](https://opendem.info/opendemeu_download_highres.html) – Europäische Höhendaten aus dem OpenDEM-Projekt; die [Hintergrundinformationen](https://opendem.info/opendemeu_background.html) dokumentieren Herkunft, Bezugssysteme und Verarbeitung.

  * [Polygon Marburg Stadtgebiet](https://raw.githubusercontent.com/gisma-courses/gc-geoinfo/master/assets/data/marburg_stadtgebiet.gpkg) – GeoPackage mit dem Polygon des Marburger Stadtgebiets.

## Aufgaben Arbeitsblatt 3

Die Ableitung und Analyse von Rasterdaten ist ein sehr weites Feld. Es umfasst über die Bildverarbeitung und Fernerkundung auch die direkte Interpretation und Analyse von z. B. Geländemodelldaten, die als Basisdaten für räumliche Analysen der realen Welt eine besonders prominente Rolle spielen. Aufgrund der langen Historie und Bedeutung gibt es eine nahezu unüberschaubare Anzahl unterschiedlichster Geländemodelldaten. Insbesondere die bekannten SRTM-Daten liegen in unzähligen Varianten vor. Darüber hinaus gibt es Daten in besserer Qualität.

Die obige Datenauswahl soll Ihnen einen Eindruck vermitteln, wo Sie überall fündig werden können, wenn Sie z. B. nach `DEM Deutschland Europa` googeln. Natürlich finden Sie zu allen Daten auch die notwendigen Informationen und können dann beurteilen, ob Sie diese für geeignet halten. Deshalb sollten Sie in den folgenden Aufgaben mindestens zwei verschiedene Datensätze verwenden.

Wichtig ist dabei, dass diese Datensätze die Erdoberfläche nicht einheitlich repräsentieren. Ein **DGM/DTM** beschreibt möglichst die reine Geländeoberfläche ohne Gebäude und Vegetation. Ein **DOM/DSM** bildet dagegen die sichtbare Oberfläche ab, also inklusive Bebauung, Bäumen und anderer Objekte. SRTM- und daraus abgeleitete Produkte liegen oft methodisch dazwischen, da sie aus Fernerkundungsdaten entstehen und je nach Produkt unterschiedlich stark korrigiert, geglättet oder modellhaft in Richtung Geländeoberfläche überführt wurden.

Die Wahl des Höhenmodells ist daher keine rein technische Entscheidung. Unterschiedliche Rasterweiten, Sensorprinzipien, Erfassungszeitpunkte, Nachprozessierungen und Höhenbezugssysteme können dazu führen, dass verschiedene Datensätze für dasselbe Gebiet deutlich unterschiedliche Höhenwerte liefern. Das beeinflusst direkt die Ergebnisse von Hangneigungs-, Sichtbarkeits-, Abfluss-, Expositions- oder Geländeschnittanalysen.

Geländemodellanalysen eignen sich deshalb besonders gut als Stellvertreter für Rasterdatenanalysen, weil an ihnen zentrale Rasterprinzipien wie Zellwerte, Auflösung, Nachbarschaftsbeziehungen, Ableitungen, Klassifikationen und Maßstabseffekte anschaulich und fachlich nachvollziehbar sichtbar werden.

## Aufgabe 03


::: {.callout-tip icon="false" appearance="simple"}
* Laden Sie mindestens zwei der oben genannten Geländemodell-Datensätze herunter. Die Daten müssen gegebenenfalls projiziert und auf die Ausdehnung des Marburger Luftbildes zugeschnitten werden.

* Prüfen Sie die Metadaten der Datensätze: Was repräsentiert der jeweilige Datensatz? Verschaffen Sie sich einen Überblick über Projektion, räumliche Auflösung, Höhenbezug und Fehlerangaben.

* Projizieren Sie die heruntergeladenen Geländemodelldatensätze nach **ETRS89 / UTM Zone 32N** und schneiden Sie sie auf den Ausschnitt des Marburger Luftbildes zu.

* Berechnen Sie für die zugeschnittenen und projizierten Datensätze **Hangneigung**, **Exposition/Aspect** und **Topographic Position Index (TPI)**. Verwenden Sie dafür z. B. das SAGA-Werkzeug **Slope, Aspect, Curvature** sowie das GDAL-Werkzeug **TPI**.

* Extrahieren Sie die Werte für **Slope**, **Aspect** und **TPI** an der Position des Brunnens auf dem Marburger Oberstadt-Marktplatz. Nutzen Sie zur Orientierung die Brunnen-Signatur in der OpenStreetMap-Webkarte.

* Wenden Sie einen **5 × 5-Mittelwertfilter** auf die Geländehöhe an und berechnen Sie anschließend erneut **Slope**, **Aspect** und **TPI**. Extrahieren Sie auch diese Werte wieder an der Position des Marktplatzbrunnens.

* Berechnen Sie unter Verwendung des Datensatzes [Marburg Stadtgebiet](https://github.com/gisma-courses/gc-geoinfo/blob/master/assets/data/marburg_stadtgebiet.gpkg) für die **ungefilterten Geländemodelle** die minimale, maximale und mittlere Hangneigung innerhalb des Stadtgebiets.

* Berechnen Sie unter Verwendung des Datensatzes [Marburg Stadtgebiet](https://github.com/gisma-courses/gc-geoinfo/blob/master/assets/data/marburg_stadtgebiet.gpkg) für die **5 × 5-gefilterten Geländemodelle** die minimale, maximale und mittlere Exposition innerhalb des Stadtgebiets.

* Stellen Sie die Ergebnisse in einer Tabelle dar.

* Benennen und begründen Sie mögliche Ursachen für Unterschiede zwischen den Ergebnissen der verwendeten Datensätze. Formulieren Sie Ihre Begründung als Stichpunktliste.
:::


## Unterstützung 

### Aufgabe 03-01

Wichtige Meta-Informationen zu den Höhendaten finden Sie auf den jeweiligen Seiten der Datenanbieter, z. B. in der [CGIAR-CSI SRTM FAQ](https://srtm.csi.cgiar.org/faq/) oder auf der offiziellen Copernicus-Seite zum [Copernicus DEM GLO-30](https://dataspace.copernicus.eu/explore-data/data-collections/copernicus-contributing-missions/collections-description/COP-DEM){:target="_blank"}. Bitte beachten Sie, dass sich die Geländemodelle zum Teil erheblich unterscheiden. Dies gilt nicht nur für das Copernicus-Modell im Vergleich zu den SRTM-Modellen, sondern auch für die SRTM-Modelle, die sich trotz gleicher Datengrundlage erheblich unterscheiden. Besonders wichtig für die erfolgreiche Bearbeitung der letzten Teilaufgabe ist daher die Auseinandersetzung mit den Metadaten.

Benutzen Sie einen der Marburg-Layer aus den vorherigen Sitzungen als Vorlage, um das Raster auf den Arbeitsbereich zuzuschneiden.

Das Stichwort für die QGIS-Hilfe zum Mittelwertfilter ist **„Nachbarn“** oder **„Filter“** im Verarbeitungswerkzeugkasten. Als Ergebnis wird z. B. `r.neighbors` aus der GRASS-GIS-Funktionssammlung angezeigt. Bei der Suche nach **„Filter“** gibt es mehrere Treffer; `Simple Filter` aus der SAGA-GIS-Funktionssammlung ist ein möglicher Einstieg, sofern SAGA in Ihrer QGIS-Installation verfügbar ist.

Mit **Zonenstatistik** können Sie sich Minimum, Maximum und Mittelwert eines Rasterdatensatzes für ein definiertes Gebiet als Tabelle ausgeben lassen. Für Marburg können Sie entweder das Stadtgebiet als Polygon digitalisieren oder nach geeigneten Verwaltungsgrenzen suchen. Ein möglicher Einstieg dafür ist der [Open-Data-Server des Bundesamts für Kartographie und Geodäsie](https://gdz.bkg.bund.de/index.php/default/open-data.html){:target="_blank"}.

Wenn Ihnen das zu umständlich ist, können Sie auch die Datei [Marburg Stadtgebiet](https://raw.githubusercontent.com/gisma-courses/gc-geoinfo/master/assets/data/marburg_stadtgebiet.gpkg) aus dem Download verwenden. Bitte beachten Sie, dass unterschiedliche Bezugsflächen auch zu unterschiedlichen Ergebnissen führen können.
