---
title: Arbeitsblatt 1 - Warm Up QGIS
title-block-banner: ../assets/images/splash_L01_1.png
title-block-banner-color: black

bibliography: ../assets/geoinfo.bib

lang: de
comments: false
---
Die Einarbeitung in komplexe Software ist mühsam und erfordert eine gewisse Frustrationstoleranz. Aufgrund der Ähnlichkeit von Softwarewerkzeugen und Konzepten ist es sinnvoll, *analoges Wissen* aufzubauen und sich den Zugang zu den Arbeitsabläufen *logisch strukturiert* und *nicht* durch *auswendig lernen* der einzelnen Arbeitsschritte zu erarbeiten. Dies wird nicht geschenkt, zumal GIS-Softwarepakete wie ArcGIS oder QGIS sehr komplexe Softwarearchitekturen darstellen.


## Worum geht es in diesem Arbeitsblatt?
Neben der Einarbeitung in neue konzeptionelle und technische Problemfelder kommt die Auseinandersetzung mit einer Softwarearchitektur mit einer ungewohnten grafischen Benutzeroberfläche (GUI) hinzu. Um diese Einstiegshürde etwas abzufedern, fangen Sie Schritt für Schritt an und beginnen in dieser ersten Einheit mit einigen grundlegenden und typischen Aufgaben, die im Wesentlichen dazu dienen, sich an die neue Software und die Datenformate zu gewöhnen.  

## Lernziele 

Nach dieser Übung können Sie
  * QGIS installieren
  * eine QGIS Projektdatei erstellen
  * Datenformate und Datenmodelle unterscheiden
  * Raster- und Vektordatensätze in QGIS öffnen
  * Eigenschaften von Datenebenen überprüfen
  * Geometrien erzeugen (digitalisieren)

## Benötigte Materialien

### Daten
  * [Digitales Luftbild](https://raw.githubusercontent.com/gisma-courses/geoinfo-basis-qgis/master/docs/assets/data/marburg_RE.tif) von Marburg und Umgebung (Beispiel RGB-Bild als Rasterdatensatz)
  * [OSM Wald Objekte](https://raw.githubusercontent.com/gisma-courses/geoinfo-basis-qgis/master/docs/assets/data/mr_nat.zip) Ausschnitt aus dem aktuellen (11/2020) Open Streetmap (OSM) Datensatz
  * [OSM Strassenobjekte ](https://raw.githubusercontent.com/gisma-courses/geoinfo-basis-qgis/master/docs/assets/data/mr_roads.zip) Auszug aus dem aktuellen Open Streetmap (OSM) Datensatz
  * [OSM POIs](https://raw.githubusercontent.com/gisma-courses/geoinfo-basis-qgis/master/docs/assets/data/mr_objects.xls) OSM points of interest (POI)  als Excel Tabelle.

### Software
  * [QGIS](https://www.qgis.org/de/site/index.html). Die aktuelle Langzeit Release ist Versin 3.22. Es emfiehlt sich sehr bei der Installation dieser Release die folgenden Installationshinweise zu berücksichtigen:
  
* **Windows** [osgeo4W Installers](https://download.osgeo.org/osgeo4w/v2/osgeo4w-setup.exe). 
* **macOS** [Mac Installationsseite](https://www.qgis.org/de/site/forusers/download.html#mac).
* **Linux** [Linux Installationsseite](https://www.qgis.org/de/site/forusers/download.html#linux). 


### Einführende Materialien

  * [Eine sanfte Einführung in GIS](https://docs.qgis.org/3.28/de/docs/gentle_gis_introduction/index.html): bietet einen gelungenen QGIS zentrierten Überblick der GI-Konzepte. Sehr zu empfehlende Zusatz-Lehrmaterialien  
  * [QGIS Benutzerhandbuch 3.28 DE](https://docs.qgis.org/3.28/de/docs/user_manual/index.html): Die aktuelle deutschsprachige Version. Es ist **die** Referenz für Nutzer. 

## Aufgaben Arbeitsblatt 1

### Aufgabe 01-01

Dieses Arbeitsblatt dient der Einführung in die verschiedenen Datenmodelle im GIS. Darüber hinaus erfahren Sie, wie Sie eigene raumbezogene Daten in das GIS importieren oder selbst im GIS z.B. durch Digitalisierung erzeugen können.

::: {.callout-tip icon="false" appearance="simple"}

  * Legen Sie bitte ein Verzeichnis an, das **ohne** Sonderzeichen und Leerzeichen (im gesamten Pfad/Verzeichnisbaum) benannt ist.
  * Erstellen Sie ein QGIS-Projekt
  * Laden Sie die Datei `marburg_RE.tif` herunter. 
  * Informieren Sie sich über die Eigenschaften des Datensatzes. (Projektion, Datenmodell, Wertebereich)
  * Legen Sie ein Unterverzeichnis mit dem Namen `data` in Ihrem Projektverzeichnis an. Laden Sie von der Downloadseite der [geofabrik] (http://download.geofabrik.de/) den Datensatz Hessen herunter. Entpacken Sie dieses Archiv in das Unterverzeichnis `data`. 
  * Nachdem Sie das Archiv entpackt haben, laden Sie die Datei `gis_osm_pois_free_1.shp` in Ihr QGIS-Projekt.
  * Informieren Sie sich über die Eigenschaften dieses Datensatzes. (Projektion, Datenmodell, Wertebereich).
  * Schneiden Sie den Datensatz `gis_osm_pois_free_1` auf die Ausdehnung des Luftbildes `marburg_RE.tif` zu. 
  * Exportieren der Punktdaten im *geopackage* Datenformat unter dem Namen `mr_points`.
  * Importieren Sie die Tabelle `mr_objects.xls` (Datensatz [Räumliche Objekte](https://raw.githubusercontent.com/gisma-courses/geoinfo-basis-qgis/master/docs/assets/data/mr_objects.xls)) als räumlichen Layer in Ihr QGIS-Projekt.
  * Erzeugen Sie aus dem Luftbild `marburg_RE.tif` mit dem Koordinatensystem **EPSG:4326 WGS84**:
      * Drei beliebige Flächen (Dateiname `mr_poly`), 
      * drei beliebige Linienzüge (Dateiname `mr_line`) 
      * zum Schluss noch 3 beliebige Positionen (Punkte) in den Layer `mr_points` einfügen.
:::


### Aufgabe 01-02 

Leider können wir Ihnen das Thema der korrekten Verortung von Geodatensätzen - also der geeigneten Projektion - nicht ganz ersparen. In Aufgabe 01-01 haben Sie Raster- und Vektordaten in QGIS importiert und eigene Vektordaten erstellt. Die räumliche Information der Daten lag jeweils in geographischen Koordinaten vor. Die von Ihnen verwendete Software QGIS führt immer eine *Echtzeitprojektion* durch, mit dem Ziel, diese Kugelkoordinaten auf den *flachen* Monitor zu projizieren. Dies hat jedoch nichts mit einer kartographisch korrekten Projektion im eigentlichen Sinne zu tun. Als Faustregel gilt jedoch, dass fast alle räumlichen Analysemethoden und geometrischen Berechnungen nur auf korrekt projizierten Daten durchgeführt werden können.



::: {.callout-tip icon="false" appearance="simple"}
* Erstellen Sie ein neues QGIS Projekt. Laden Sie zuerst die Rasterdatei `marburg_RE.tif` und dann die Vektordatensätze `mr_roads` und `mr_nat`.
   * In welchen Projektionen liegen die einzelnen Datensätze vor?
   * In welcher Projektion werden die Daten dargestellt? 
   * Wo kann die Projektion für die Darstellung der Daten definiert werden?
   * Welche Probleme können bei der Projektion *on-the-fly* oder *in-Echtzeit* auftreten?
:::

::: {.callout-warning icon="false" appearance="simple"}
Für den Anfang können wir Ihnen nur dringend empfehlen, das CRS (Coordinate Reference System) bzw. KBS (Koordinatenbezugssystem) Ihres *Projektes* und jeder Datenebene identisch zu halten. Für Deutschland ist das offizielle System [ETRS89 UTM 32 ](https://epsg.io/25832). Durch diese Sorgfalt können Positionierungsfehler und damit einer der häufigsten Alltagsfehler in der GIS-Welt vermieden werden.
:::

### Gewichtung der Aufgaben in Arbeitsblatt 1

| Aufgabenteil | Gewichtung Teilaufgabe | Gewichtung  Gesamt| 
|:-------------|:----------------------:|:-----------------:|
|Aufgabe 01-01 | 0.5  | 0.05  | 
|Aufgabe 01-02 | 0.5  | 0.05  | 
|**Aufgabe 01**    | **1.0**  | **0.1**  | 


## Unterstützung 

Als konkreten Einstieg in die Bearbeitung von Aufgabe 1 möchten wir Ihnen einige Einstiegshilfen für QGIS anbieten. QGIS ist ein komplexes Softwareprodukt, das nicht nur in verschiedenen Versionen auf allen gängigen Betriebssystemplattformen verfügbar ist, sondern darüber hinaus auch vollständig anpassbar ist. Aus diesem Grund kursiert eine Vielzahl von Hilfestellungen, Handbüchern und Tutorials im Netz - bei weitem nicht jeder Google-Treffer ist geeignet und nicht jedes Tutorial passt zu der von Ihnen verwendeten Version.

Eine erste Anlaufstelle für konkrete Informationen ist die integrierte Hilfe des Softwarepakets. Darüber hinaus steht eine umfangreiche Dokumentation zur Verfügung. Die jeweils aktuelle [QGIS Landing Page] (https://www.qgis.org/de/site/forusers/index.html) ist der zentrale Zugang zu allen offiziell vom Projekt zur Verfügung gestellten Dokumentationen. 

Für alle Hilfeseiten gilt: Stellen Sie **unbedingt** sicher, dass Sie die Hilfe für die entsprechende QGIS Version aufrufen. Falls diese (noch) nicht verfügbar ist, versuchen Sie es mit der nächsten Vorgängerversion und am besten mit der englischen Hilfe, da diese die Referenz für alle Übersetzungen darstellt. 

::: {.callout-warning icon="false" appearance="simple"}
**Achtung** Der Übergang von QGIS2.x zu QGIS3.x hat grundlegende Änderungen mit sich gebracht. Die Tutorials und Hilfen von QGIS 2.x sind für die aktuelle Version praktisch **unbrauchbar**. 
:::

### Einrichten eines QGIS Projektes 

Bei Rechnern mit einem Home-Verzeichnis in der Cloud/im Netzwerk (z.B. im Uni-Pool) empfehlen wir **dringend**, die Daten auf einer **lokalen Festplatte** zu speichern.  Dazu müssen Sie zunächst eine Ordnerstruktur für Ihr Projekt anlegen. Hilfe zur Projektdatei finden Sie unter [Arbeiten mit Projektdateien] (https://docs.qgis.org/3.28/de/docs/user_manual/introduction/project_files.html). 

::: {.callout-warning icon="false" appearance="simple"}
Bitte achten Sie unbedingt darauf, **keine** Sonderzeichen, Umlaute oder Leerzeichen zu verwenden. 
:::

### Digitalisierung von Geometriedaten

Die manuelle Erzeugung von Vektordaten wird allgemein als *Digitalisieren* bezeichnet. Dabei erzeugen Sie eigene vektorbasierte Datensätze aus z.B. Rasterbilddateien wie Satellitenbildern, Luftbildern, thematischen und topographischen Karten, einfachen Screenshots oder anderen Vorlagen. Siehe dazu die QGIS Hilfe zur [Digitalisierung] (https://docs.qgis.org/3.28/de/docs/user_manual/working_with_vector/editing_geometry_attributes.html). Ein ausführliches Anwendungsbeispiel finden Sie unter [Digitizing Forest Stands](https://docs.qgis.org/3.28/en/docs/training_manual/forestry/stands_digitazing.html).

### Vektordaten beschneiden 
Diese Aufgabe ist ein gutes Beispiel dafür, wie knifflig die Suche nach Hilfe sein kann. Natürlich kann man immer im Internet suchen. Versuchen Sie es zum Beispiel mit "*vektordaten zuschneiden qgis*". Sie werden viele Treffer erhalten, aber wenn Sie genau hinsehen, werden Sie nichts über das Zuschneiden von Vektordaten mit Hilfe einer Rasterdatei finden. Was passiert beim Beschneiden? Offensichtlich müssen Sie einem Werkzeug mitteilen, was die gewünschte Ausdehnung ist. Fangen Sie mit diesem Wissen noch einmal an. Nur diesmal benutzen Sie die Werkzeugleiste und geben "*cut*" oder "*clip*" ein. Einige Ergebnisse werden angezeigt. Unter anderem auch *Vektor auf Ausdehnung schneiden*. Wenn man diesen auswählt, kann man drei Optionen für die *Ausdehnung* wählen...

### Tabellen in QGIS importieren
Das Importieren von Tabellen birgt einige Fallstricke. Generell können Tabellendaten in QGIS nur verwendet werden, wenn sie entweder selbst Koordinaten (d.h. geographische Informationen) enthalten oder wenn sie einen Schlüssel wie z.B. eine ID enthalten, der bereits vorhandenen Geometriedaten zugeordnet werden kann. Generell können sie aber dem folgenden Schema folgen:
[Import von Tabellenkalkulationen oder CSV-Dateien](http://www.qgistutorials.com/de/docs/3/importing_spreadsheets_csv.html).

### Arbeiten mit Projektionen
Das Kapitel 
[Arbeiten mit Projektionen](https://docs.qgis.org/3.28/de/docs/user_manual/working_with_projections/working_with_projections.html) ist für Anfänger:innen nicht ganz leicht zu erarbeiten. Wichtig ist hier vor allem die richtige Zuordnung von Projektionen. Für die Umprojektion von Vektordaten lohnt sich ein Blick auf [Reprojecting and Transforming Data](https://docs.qgis.org/3.28/de/docs/training_manual/vector_analysis/reproject_transform.html).