---
title: "Formales"
title-block-banner: ../assets/images/splash-geoinformatik.jpg
title-block-banner-color: Black
lang: de
comments: false
---

Die Aufgaben im Reader und die Übungsblätter auf den Kursseiten bilden die Grundlage für die Studien- und Prüfungsleistungen.

## Anwesenheit

Die Übungen zu diesem Kurs finden grundsätzlich als **Präsenzveranstaltung** statt. Obwohl bekanntlich keine rechtlich verbindliche Anwesenheitspflicht besteht, ist Ihre Anwesenheit erwünscht und erforderlich, da der Kursverlauf maßgeblich durch Ihre Frage- und Diskussionsbeiträge bestimmt wird. In begründeten Ausnahmefällen können einzelne Sitzungen online oder per Streaming durchgeführt werden.

## Übersicht der Kommunikationsformen

### Diese Website

Diese Webseite dient der einseitigen und überwiegend asynchronen Kommunikation und der Bereitstellung von Lern-/Lehrmaterialien.

### Kursbereich in Ilias

Der \[Kursbereich der Lernplattform PUM Ilias\] (https://ilias.uni-marburg.de/login.php?target=&client_id=UNIMR&auth_stat=) dient der Organisation des Kurses, der Bereitstellung der urheberrechtlich geschützten Materialien, der Bereitstellung weiterer Kommunikationsformate, den obligatorischen Self-Assessments und der Abgabe der Projektarbeit.

### Fragen

Wenn Sie Fragen haben, nutzen Sie bitte in erster Linie die Präsenzzeiten des Seminars. Prüfen Sie zunächst, ob Ihre Fragen bereits in Form von Screencasts und FAQ-Einträgen vorhanden sind. Sollten Sie darüber hinaus Fragen haben, senden Sie diese bitte per E-Mail mit dem Betreff \[Geoinfo SoSe<Jahr>\] oder \[Geoinfo WiSe<Jahr>\] (im Platzhalter Jahr tragen Sie bitte das aktuelle Semesterjahr ein).

## Zeitaufwand und Ablauf

Jede Kurseinheit dauert eine Woche und besteht aus einem Lern- und einem Übungsteil. Die Übungsblätter werden bei Bedarf oder Rückfragen in der folgenden Kurseinheit besprochen.

### Kursverlauf SoSe 2024

| Sitzung | Datum  | Thema                                                 | Ergebnissicherung                                |
|:----------:|------------|--------------------------|:----------------------|
|    1    | 17.04. | Orga/ Einführung in geographische und GI Raumkonzepte |                                                  |
|    2    | 24.04. | Vektordaten & Attributtabellen                        | Einführung in geographische und GI Raumkonzepte  |
|    3    | 29.04. | Rasterdatenanalyse                                    | Vektordaten & Attributtabellen                   |
|    4    | 08.05  | Kostenanalyse                                         | Rasterdatenanalyse                               |
|    5    | 15.05. | Interpolation                                         | Kostenanalyse                                    |
|         |        | WrapUp                                                | Unabhängige Wiederholung des methodischen Inputs |
|    6    | 05.06. |                                                       | F&A Alle Themen                                  |
|    7    | 12.06  | Automatisierung von Arbeitsabläufen in QGIS           |                                                  |
|    8    | 19.06  | Projektarbeit                                         | Automatisierung von Arbeitsabläufen in QGIS      |
|    9    | 26.06. | Präsentation der Projektarbeitkonzepte mit Feedback   |                                                  |
|   10    | 03.07. | Projektarbeit                                         | Beratung                                         |
|   11    | 10.07. | Projektarbeit                                         | Beratung                                         |
|   12    | 17.07. | Projektarbeit                                         | Beratung                                         |
|         | 31.07. | Abgabe Projektarbeit                                  | Beratung                                         |

### Anforderungen und Zeitaufwand

Der Kurs ist standardmäßig auf 6 Leistungspunkte (LP/ECTS) gemäß der Zeiteinteilung nach den Bologna-Kriterien ausgelegt. Umgerechnet in Zeit entspricht dies 180 Stunden/Person. Dies ist die Zeit, die ein durchschnittlicher Studierender nach den Bologna-Kriterien benötigt, um ein zufriedenstellendes Ergebnis zu erzielen. Da diese Leistung mit 5 Lehrveranstaltungen/Semester zu erbringen ist, müssten 60 Arbeitsstunden pro Woche erbracht werden. Dieses Bologna-Standardszenario halten wir für realitätsfern. Zieht man davon die vorlesungsfreie Zeit ab, verbleiben ca. 90 Stunden, um die geforderten Kenntnisse und Kompetenzen von 180 Stunden zu erwerben - ebenfalls realitätsfern. Ein gangbarer Kompromiss besteht darin, etwa die Hälfte der vorlesungsfreien Zeit in den Lehrbetrieb zu integrieren, so dass 135 Stunden für 6 ECTS, also 9 Stunden pro Woche, verbleiben. Dies ist anspruchsvoll, aber machbar. Die Aufwandskalkulation gilt trotz Halbierung der Stundenzahl auch für die 3 LP/ECTS-Variante, da der Kurs in der Mitte des Semesters mit einer Klausur abgeschlossen wird.

### Exemplarischer Stundenplan der Lehrveranstaltung

-   Präsenz: 2 Stunden pro Woche
    -   Der Kurs besteht für jede Gruppe aus einer Input-Sitzung und einem zugehörigen Seminar (Zeiten siehe Ilias).
-   Selbststudium: 7 Stunden pro Woche
    -   Wöchentliche Arbeitszeiten
    -   Wöchentliche Treffen mit Kommiliton:innen
    -   Wöchentliche Hausarbeit
    -   Bearbeitung der Abschlussarbeit

Die folgende Abbildung zeigt beispielhaft eine **mögliche** Verteilung dieser notwendigen/verfügbaren Arbeitszeiten. Diese Zeiten sind aus didaktischen Gründen exemplarisch über die Woche verteilt und beinhalten sowohl Zeiten in der Lerngruppe als auch Zeiten des Selbststudiums. Natürlich können Sie sich auch anders organisieren.

<iframe width="100%" height="800px" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSTEUhTD7NO-_kW9QUvdfbby2KOWUBDNMBN6InTs4u0bqhNRwxESLe7nvxn_VbSEwpjgj7S5SeJ2_wZ/pubhtml?widget=true&amp;headers=false">

</iframe>

::: {.callout-tip icon="false" appearance="simple"}
Beispielhafter Stundenplan für die Lehrveranstaltung Geoinformatik. Der Gesamtaufwand ist mit 11 Stunden pro Woche inklusive Präsenzzeit kalkuliert. Die Planung, Blockung und Aufteilung in Selbststudium und Lerngruppen ist wünschenswert, muss aber selbstredend den eigenen Bedürfnissen angepasst werden.
:::

## Studienleistung

Die individuell zu erbringende Studienleistung wird durch das erfolgreiche Absolvieren der Self-Assessment-Einheiten in Ilias erbracht. Dazu müssen 3 der 5 Einheiten bis zu dem im Ilias-Kurs angegebenen Termin mit mindestens ausreichend bestanden werden.

## Prüfungsleistung

Im Anschluss an die 5 Übungsblöcke wird eine Präsenzklausur mit praktischem Prüfungsanteil für 3 LP/ECTS oder eine Projektarbeit für 6 LP/ECTS abgelegt. Dazu bearbeiten Sie ein eigenständiges/vorgegebenes kleines Projekt. Die Abgabe des wissenschaftlichen Projektberichts (4-6 Seiten) stellt die Grundlage der zu bewertenden Leistung dar.

::: callout-important
Die Prüfungsleistung in Form einer Projektarbeit ist grundsätzlich individuell zu erbringen, kann aber auch in 2er Gruppen erbracht werden, wenn die Anteile kenntlich gemacht werden.
:::

### Gewichtung der Übungen

Die Übungsaufgaben werden gewichtet. Die Gewichtung der Übungsaufgaben entspricht in etwa den methodischen Fertigkeiten, die in die Projektarbeit einzubringen sind. Das bedeutet, dass Sie in der Regel \> 50% der vermittelten Methoden (oder äquivalenter Methoden) in die Projektarbeit einbringen müssen. Damit wird sichergestellt, dass ein gewisses Anspruchsniveau erreicht wird. Da die Projektarbeit in der Regel schrittweise entwickelt wird, erfolgt die Einschätzung eines ausreichenden Anspruchsniveaus in Absprache mit der Kursleitung. Die Gewichtung der einzelnen Kenntnisse und Fertigkeiten ist der Aufgabenstellung zu entnehmen.

### Bewertungskriterien Projektarbeit

Im folgenden [Bewertungsleitfaden](https://docs.google.com/document/d/1OFLIm8IEBQKYhaFDggTUswrBG_N58jeh/edit?usp=sharing&ouid=116863676082637149781&rtpof=true&sd=true) finden Sie die als ***verbindlich vorausgesetzten*** Formalia für die Beurteilung, die Definition der verwendeten Begriffe sowie Beurteilungskonzepte und Erwartungshorizonte. Bei Fragen und Anmerkungen wenden Sie sich bitte an Ihre Dozent:innen.

<iframe width="100%" height="650" allowfullscreen="true" src="https://docs.google.com/document/d/e/2PACX-1vQzz7W33uJOsuUh7fJ2wjliBY764-Edd71T3d2tGeuh5dJ8zZGE-8tgOTI9Adf4Jw/pub?embedded=true">

</iframe>

### Einreichungen

Die Ausarbeitung soll grundsätzlich (alles inbegriffen) **2500 Wörter** nicht überschreiten. Sie ist als **PDF-Datei** mit den als wichtig erachteten Abbildungen abzuspeichern und gemäß den [formalen Anforderungen](#formale-anforderungen) einzureichen.

::: {.callout-warning appearance="simple" icon="false"}
Eine Unter-/Überschreitung von mehr als 10 Prozent führt zu einem Abzug von 1 Notenpunkt pro 10 Prozent.
:::

Als Orientierungshilfe finden Sie im Reader *Projektarbeit* den beispielhaften Aufbau einer solchen Arbeit.

Grundsätzlich sind Studien- und Prüfungsleistungen im [Kursbereich der Lernplattform PUM Ilias](https://ilias.uni-marburg.de/login.php?target=&client_id=UNIMR&auth_stat=) fristgerecht und unter Berücksichtigung der [formalen Anforderungen](#formale-anforderungen) eingereicht werden. Ausnahmen sind nur in begründeten und vorher abgesprochenen Fällen möglich.

<a name="formale-anforderungen"></a>Formale Anforderungen {#formale-anforderungen}

Bitte reichen Sie die Übungsaufgaben innerhalb einer Kurseinheit **ausnahmslos** als PDF-Datei ein. Benennen Sie die PDF-Datei wie folgt

`Aufgabe_X_<Nachname>_<Vorname>.pdf` (z.B. Aufgabe_1_Reudenbach_Chris.pdf\_).

::: {.callout-tip appearance="simple" icon="false" title="Tipp"}
Verwenden Sie ein Textverarbeitungsprogramm wie z.B. Microsoft Word, ONLYOFFICE oder OpenOffice zur Erstellung der Abgabedatei und erzeugen Sie mit diesen Werkzeugen **eine** PDF-Datei. Kontrollieren Sie unbedingt, ob die fertige PDF-Datei Ihren Vorstellungen entspricht.
:::

Fügen Sie in die Kopfzeile Ihren Namen und Ihre Matrikelnummer nach folgendem Schema ein:

`Nachname, Vorname, Matrikelnummer` (z.B. Reudenbach, Chris, 1234567).

Bitte geben Sie nur die **überprüfte Endfassung** in den jeweiligen ILIAS-Abgabeordner ein.

## Kurszeiten

Kurszeiten Mittwoch, 12:15-13:45 Uhr
