
---
title: "Raumrepräsentation in der Geoinformatik"
title-block-banner: ../assets/images/01-splash.jpg
title-block-banner-color: black
format:
  html:
    other-links:
      - text: "Splash Source: Snow (1855):"
        href: https://w.wiki/QtV
bibliography: ../assets/geoinfo.bib

lang: de
comments: false
---



Wenn wir die reale Welt, im Folgenden auch als reale Welt oder Realwelt bezeichnet, in Form einer Karte oder in einem Geoinformationssystem abbilden wollen, müssen wir abstrahieren. Das bedeutet, dass wir einzelne Aspekte der realen Welt in den Mittelpunkt unserer Darstellung stellen und sie so weit vereinfachen und verallgemeinern, dass sie mit den uns zur Verfügung stehenden Methoden tatsächlich abgebildet werden können.


Beispielsweise kann man in einer auf Papier gedruckten Karte (2D) kein mit Händen greifbares Hochhaus (3D) darstellen, aber man kann z.B. eine perspektivische Zeichnung eines Hochhauses einfügen. Das in irgendeiner Form gezeichnete Hochhaus ist also ein Abbild des realen Hochhauses. Es repräsentiert in unserem Bild das Hochhaus, weshalb man auch von einer Repräsentation oder einer Repräsentation der realen Welt spricht.

## Reale Welt oder Modell?

Eine Abbildung von etwas, also auch eine Abbildung von Teilen der realen Welt, wird allgemein als Modell bezeichnet. Wenn wir den Ausschnitt der realen Welt, der uns gerade interessiert, als System bezeichnen, dann können wir die Bestandteile dieses Systems als Systemkomponenten oder einfach als Komponenten bezeichnen. Ein Beispiel: Wenn Sie Ihre Geoinformatik-Kenntnisse im Kontext der Stadtgeographie anwenden, könnte der Ausschnitt der realen Welt eine Stadt sein. Diese Stadt wäre dann das betrachtete System und die einzelnen Häuser, Straßen, Menschen, Firmen, Restaurants etc. sowie die Beziehungen zwischen diesen, die Systemkomponenten. Natürlich müssen Sie auch die Beziehungen zu Nachbarstädten in Ihre Analyse einbeziehen, aber diese Beziehungen könnten Sie auch als Randbedingungen in Ihre Systemvorstellung einbauen. Bezogen auf die Ihnen bereits vertraute Kartographie könnte dieses Konzept in einer Stadtkarte münden, in der z.B. die Verkehrsströme zwischen den auf dem Stadtplan verzeichneten Unternehmen und den mittags besuchten Restaurants visualisiert werden. Für Personen, die außerhalb der Stadt wohnen (d.h. außerhalb des Systems bzw. des Stadtplans) und extra anreisen, um diese Restaurants zu besuchen, könnte die Visualisierung dieser Verkehrsströme am Rand der Karte beginnen (z.B. in Form von Pfeilen, die vom Kartenrand entlang von Eisenbahnlinien oder Einfallstraßen in die Stadt verlaufen).

Die Abstraktion der realen Welt ist also eine Form der Modellierung. Das mag für den einen oder anderen ungewohnt sein, denn im studentischen Alltag denkt man beim Begriff Modellierung vielleicht an statistische Modelle, Klimamodelle oder ähnliches, obwohl jeder von uns schon einmal mit Spielzeugautos oder Puppenwagen und damit mit Modellen (von echten Autos, von Kinderwagen) gespielt hat, aber nur die wenigsten schon einmal ein Klimamodell programmiert haben. Und um dem nächsten Missverständnis vorzubeugen: Modelle müssen nicht greifbar sein. Ein Modell im Kopf, das uns den Weg zur Mensa zeigt, ist genauso wenig greifbar wie ein Datenmodell im Computer.

Wie bereits im Abschnitt [Geographische Abstraktion](../unit01/unit01-02.html) diskutiert, hängt das Ergebnis der Abstraktion, also der Modellierung von Ausschnitten der realen Welt und deren Darstellung im Modell, von der jeweiligen Zielsetzung, den zur Verfügung stehenden Mitteln und Methoden und - ganz wichtig - von der kognitiven Wahrnehmung des Bearbeiters ab. Letzteres bedeutet, dass selbst bei gleicher Zielsetzung und gleicher Methodenwahl die Abstraktion der realen Welt und ihre Repräsentation im Modell völlig unterschiedlich sein können.

## GI-Raumkonzepte

Bei der Abstraktion von räumlichen Eigenschaften der realen Welt spielen Raumkonzepte eine wichtige Rolle. Bereits in der Kindheit lernen wir durch Erfahrung, vom Raum zu abstrahieren. Beispiele dafür sind die Vorstellung von Enge oder Nähe. Entsprechende Beispielaussagen wären: „Die Fische sind im Aquarium“ und „Die Großeltern, die in der gleichen Straße wohnen, sind näher (räumlich und zeitlich!) als Oma und Opa, die in der (400 km entfernten) Stadt wohnen“. Bei der Nutzung von Geographischen Informationssystemen erfinden wir diese Kategorisierungen nicht neu. In der computerbasierten, also digitalen Repräsentation der realen Welt werden diese Alltagskonzepte in so genannten Datenmodellen abgebildet. Datenmodelle stellen spezifische formale Strukturen und Regeln bereit, um Komponenten der realen Welt und ihre Beziehungen durch Daten abzubilden. Abstrahiert man diesen Zusammenhang, so spricht man auch von Ontologien zur Ableitung von Wissen über die reale Welt. Eine Ontologie zur Strukturierung räumlichen Wissens ist bereits in Form von Karten aus [Geographische Abstraktion](../unit01/unit01-02.html) bekannt.

## Lernziele

Nach dieser Sitzung sollten Sie

-   die Bedeutung der Repräsentation der realen Welt durch Daten verstehen
-   die Begriffe kontinuierlicher Raum und diskrete Objekte im Raum unterscheiden können
-   die Konzepte von Geoobjekten und Geodaten und ihre digitale Repräsentation als Konzepte zur Kodierung der realen Welt kennen.

::: {#cite  style="color: transparent;"}
@snow
:::
